### ISSUE TITLE
程序意外终止

### ISSUE THREAD

**Issue by JImumu** [Rocket1184/qq-bot-rebown#26]
此次程序终止放生再第一次扫码登录（第一次保存cookie）24小时之后，24小时之间有过重新启动程序。
错误信息如下：
[Mon Mar 26 2018 15:48:10 GMT+0800 (中国标准时间)] WARNING [loopPoll] Request Failed:  { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',

**Comment by rocka** [comment]
有一个 `continue` 写错位置了，所以 `socket hang up` 的时候会导致程序中止。

https://github.com/Rocket1184/qq-bot-rebown/blob/89466a7a4a3e53c66576b3396687e58e5b8c7597/src/qq/index.js#L544-L555

这个 `continue` 应该放在 `if` 外面，请求出错的时候应该跳过消息处理的过程。

至于为什么 `socket hang up` ，应该是网络问题，我只遇到过一两次，没法确定

**Comment by rocka** [comment]
should be fixed by 9e19a8a
