### ISSUE TITLE
账号密码登录超时

### ISSUE THREAD

**Issue by JImumu** [Rocket1184/qq-bot-rebown#27]
以下是运行时的全部日志：
[Tue Mar 27 2018 10:46:11 GMT+0800 (中国标准时间)] INFO (-/5) 帐号密码登录
[Tue Mar 27 2018 10:46:49 GMT+0800 (中国标准时间)] ERROR Login with puppeteer:
 Error: waiting failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (D:\Work\QQBot2\node_modules\puppeteer\lib\FrameManager.js:793:58)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[Tue Mar 27 2018 10:46:49 GMT+0800 (中国标准时间)] ERROR Screenshot saved to C:\Users\JIM\AppData\Local\Temp\qq-bot-rebown-shcSAN\1522118809065.png

**Comment by JImumu** [comment]
查看图片为拖动滑块的验证码，初步断定 账号密码登录不可用

**Comment by rocka** [comment]
异地登录会要求图形验证码，打开浏览器隐身模式，登录 [QQ 空间手机版](https://m.qzone.com) 几次，不要让它以为你是异地登录。
