### ISSUE TITLE
账号密码登录的方式无效

### ISSUE THREAD

**Issue by fa-ge** [Rocket1184/qq-bot-rebown#33]
`
const qq = new QQ({
    app: {
        login: QQ.LOGIN.PWD,
    },
    auth: {
        u: 'qq号',
        p: '密码',
    },
})
`
会有下面报错

[Mon Jul 09 2018 15:13:46 GMT+0800 (CST)] ERROR Login with puppeteer:
 TypeError: Cannot read property 'click' of null
    at Object.getTokens (/Users/fage/Documents/workspace/js/qiangdahongbao/wechat-robot/node_modules/.2.1.8@qq-bot-rebown/src/qq/headless.js:40:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
[Mon Jul 09 2018 15:13:47 GMT+0800 (CST)] ERROR Screenshot saved to /var/folders/03/3xqpky1d2vvfg1n2xp06b28h0000gn/T/qq-bot-rebown-FuaEhy/1531120426788.png

发生错误的代码是在这一块

`
  if (ptLoginURL.startsWith('https://xui.ptlogin2.qq.com/cgi-bin/xlogin')) {
            ptLoginFrame.waitFor('#qlogin_list a.face');
            log.debug('Clicking avatar...');
            const avatar = await ptLoginFrame.$('#qlogin_list a.face');
            await avatar.click();
        }
`
我人工去点击了一下这个div，跳转链接是这个https://xui.ptlogin2.qq.com/cgi-bin/&regmaster=&aid=501004106&s_url=http%3A%2F%2Fweb2.qq.com%2Fproxy.html，404啦

**Comment by rocka** [comment]
现在好像根本不能出现点击头像登录的界面了，所以这个功能已经废了 ...

**Comment by shoutwikis** [comment]
不好意思，我想懒惰地问下，现在是否还有稳定的，且基于javascript的qqbot? (鉴于以上对话，好像这些工具都因webqq网页的改变而无法登陆了。最后，我不知我是否真会要个属于自己的qqbot，因此，不必为我的这些问题分心，何况我的回复其实是离题了。刚才仅是出于好奇才发问。谢谢，抱歉，打扰了)

**Comment by rocka** [comment]
@shoutwikis 想要稳定，可以考虑 酷Q 的 HTTP API ，没有语言限制。

关于本项目，只是账号密码登录的方式废掉了，只能通过手机 QQ 扫描二维码来进行登录，其他的 SmartQQ 实现应该也是一样。
