### ISSUE TITLE
QQ Bot got an error after join a new group

### ISSUE THREAD

**Issue by kyya** [Rocket1184/qq-bot-rebown#34]
将机器人同学加入一个新的群（共3人）后，使用 `QQ.getGroup()` 可以获取该群信息。
群员在群内发送任意消息后产生报错。
```
(node:9034) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at QQ.getNameInGroup (/home/kiko/REPO/qqbot/node_modules/qq-bot-rebown/src/qq/index.js:439:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9034) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kyya** [comment]
+ Node version `v10.7.0`
+ 已尝试重新获取 Cookie

**Comment by kyya** [comment]
Bug 同 #16 
解决方案：随便设置个群名片
